### PR TITLE
修正 ANCM 有幾個其他涵式： 的語意

### PR DESCRIPTION
**Pull request by SkyChang**
ANCM 有幾個其他涵式：
改成
ANCM 有幾個其他功能：

這邊指的應該不是涵式，而是功能

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C30%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201710301559443611-14%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7flfl6fmtzv%2B29fqKLZgPzvathiYlo1t0xnVXsZtpTU%3D&st=2017-10-30T15%3A54%3A47Z&se=2017-11-30T15%3A59%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
@SkyChang  您好，我們仍然在討論您的建議，會儘速於稍後做出結論。  	  	
感謝您的支持，  Microsoft C&E 當地語系化小組敬上

**Comment by gosali** [comment]
@SkyChang  您好，感謝您的意見反應及建議！  
  
 我們會將您的建議納入考量，此文章會在下次當地語系化時發佈。 
  
 Microsoft C&E 當地語系化小組敬上

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711061937295753-14%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gVLpknS1lOhZxSGVtsPL4NR5B2XG1rXWMOI%2FQdPm5I8%3D&st=2017-11-06T19%3A34%3A03Z&se=2017-12-07T19%3A39%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711061939091234-14%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SQgieFO%2FVh%2FCDyDb9qcv0KV1UUWeFEKLaF%2Fx%2FRod8%2Fs%3D&st=2017-11-06T19%3A34%3A47Z&se=2017-12-07T19%3A39%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711061940096770-14%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XAV95ijO3QuE0NtMEGglBesW2QExp%2FbX0WBLmRaP%2Bpo%3D&st=2017-11-06T19%3A35%3A43Z&se=2017-12-07T19%3A40%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
