### PR TITLE
翻譯有誤

### PR DESCRIPTION
**Pull request by SkyChang**
Kestrel 會接聽來自 ANCM 流量。  ANCM 指定環境變數在啟動時，透過的連接埠和[UseIISIntegration](#call-useiisintegration)方法會設定伺服器接聽`http://localhost:{port}`。 沒有額外的檢查拒絕不是從 ANCM 的要求。
英文原文為
Kestrel listens for traffic coming from ANCM. ANCM specifies the port via environment variable at startup, and the UseIISIntegration method configures the server to listen on http://localhost:{port}. There are additional checks to reject requests not from ANCM. 
從原文可以看到，這邊講的是 Kestrel 監聽，而最後一句 There are additional checks to reject requests not from ANCM. 從上下文可以得知，Kestrel 監聽，會去檢查不是從 ANCM 來的，並且拒絕，但翻譯的文章寫成
"沒有額外的檢查拒絕不是從 ANCM 的要求"，和原文有點落差，建議修改成 "並且還有一些額外的檢查來拒絕不是來自 ANCM 的請求。 "

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C30%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201710301544370856-12%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=W8NT2X%2B9iNH8%2FlvWHmRYzViUJjCo5%2FCp0%2Bb5fJxP24Q%3D&st=2017-10-30T15%3A39%3A42Z&se=2017-11-30T15%3A44%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @SkyChang , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
@SkyChang , Thank you for your feedback and suggestion! 
  
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
  
Microsoft C&E Localization Team

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711061925005681-12%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=h0%2BepbtBjosHQiTh4NC5HApGVg5mPEEdT7L4Sf%2BFdEw%3D&st=2017-11-06T19%3A20%3A27Z&se=2017-12-07T19%3A25%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711061925252153-12%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Y1%2FyA88HJS4tBBZ9we09FmvQeqH1hXGJVf9aK5dAmms%3D&st=2017-11-06T19%3A20%3A51Z&se=2017-12-07T19%3A25%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
