### PR TITLE
修正中文語意錯誤

### PR DESCRIPTION
**Pull request by SkyChang**
因為處理序中執行的 ASP.NET 核心應用程式是由 IIS 工作者處理序分開，ANCM 也沒有處理序管理。
但原文是
Because ASP.NET Core applications run in a process separate from the IIS worker process, ANCM also does process management. 
所以應該是 "由於 ASP.NET Core 應用程式的處理序與 IIS 工作者處理序分開運行，所以 ANCM 還進行處理序管理。"

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C30%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201710301524065529-11%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=A0UOCUpDU%2FnHCbykb%2FfFegrDwmbK89Essl0lXtImYMM%3D&st=2017-10-30T15%3A19%3A12Z&se=2017-11-30T15%3A24%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @SkyChang , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@SkyChang ：感謝您的意見反應及建議！   	  	
我們十分重視您的意見反應，同時對您的意見反應進行部分調整，以便符合 Microsoft 樣式指南。我們會在下次當地語系化時發佈此文章。  	  
Microsoft C&E 當地語系化小組敬上

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711061930095900-11%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qPsJqyHpjvHPK5LxHyaszDQEkeqHin9uBCy17Fl7NYo%3D&st=2017-11-06T19%3A26%3A35Z&se=2017-12-07T19%3A31%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711061933489776-11%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QAsr7YAymgL%2BgCYCPBrRtoSLtvzWXcvZCyl020XX5Tk%3D&st=2017-11-06T19%3A30%3A18Z&se=2017-12-07T19%3A35%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
