### PR TITLE
make it clear of Chinese text translation

### PR DESCRIPTION
**Pull request by iangithub**
make it clear of Chinese text translation

### CODE REVIEW

**Comment by gosali** [comment]
Hi @iangithub , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hi @iangithub  Thank you for your feedback and suggestion! 
		
Our linguistic moderator rejected the suggestions for not being compliant with our style guide. We are closing this PR.
		
Microsoft C&E Localization Team

**Comment by iangithub** [comment]
Hi ,
Thanks , Where can I find the style guide?

**Comment by DavidPrio** [comment]
Hi @iangithub 
I apologize for the long wait on a reply.
Please let me paraphrase and explain further the reasons for your contributions not being implemented. On the one hand, our specialized language moderator has reported the text does not fully adheres to the linguistic standards required for Microsoft documentation. On the other hand, terminology used does not seem consistent with MS TermStudio (glossary), where "plain old 'X' object" is localized and approved as "純舊 'X' 物件". In case you need further justification, we can certainly contact our language moderator. We truly appreciate your feedback and are willing to review other items you consider are worth revising.
Best regards

Microsoft C&E Localization Team

**Comment by Sara-Nicolini** [comment]
Hi @iangithub, 

For future reference, you can consult the Microsoft Language Portal. On this site, you can run a search for approved terminology and download a copy of the Microsoft Style Guide - https://www.microsoft.com/language/StyleGuides. 

Regards,
Sara Nicolini

**Comment by DavidPrio** [comment]
Hi @iangithub, adding right link to Style Guide https://www.microsoft.com/zh-cn/language/StyleGuides. i hope this helps. Warm regards

Microsoft C&E Localization Team

**Comment by iangithub** [comment]
@DavidPrio 
"plain old 'X' object" is localized and approved as "純舊 'X' 物件". I have to say that just word to word translation , nobody can understand what's ""純舊 'X' 物件" , i think the translation document is serving local people , not just translation word by word , the important thing is easy to understand , i am a Taiwan people and MVP for 6 years , i think about writing , reading and speak use "zh-tw" language , I'm better than you , just like use english you better than me, I'm helping you to translate "zh-tw" documents, i hope have any one Taiwan people in your organization to review  "zh-tw" documents translation request . Hope you could understand.

**Comment by v-radelg** [comment]
Hi @iangithub 

We are going to contact our Traditional Chinese language moderator to double check his decision about the suggestions and if they apply we will gladly accept and merge them.

Thank you for your support
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hi @iangithub 

Below you can find the detailed explanation from our traditional chinese language moderator.


" So-called MS convention is that "Plain Old X Object" is approved as "純舊 X 物件" in TS since 4th April 2012 (Target ID 1703391.)
So we couldn't take this suggestion since that will violate the compliance to the Term Studio.

所謂的 MS 慣例，係指 "Plain Old X Object" 自 2012 年 4 月 4 日起，即在 TS 中定為 "純舊 X 物件" (目標語編號 1703391)，
這便是我們無法採納建議的主要原因，因為會損及譯文與 TS 的合規性. "


" So-called 'grammatical' is described below (所謂「合呼文法」簡述如下):
1.	[V store] is the main action of this phrase. ([V store] 為本片語之主要動作。)
2.	[NP to-do items] is the Object of the main action. ([NP to-do items] 為主要動作的賓語。)
3.	[PP in an in-memory database] indicates the place where the action occurs. ([PP in an in-memory database] 則指出了動作發生的處所。)
So according to the Modern Chinese Grammar, in the translation, the Location role represented as a PP should come before the verbal unit (since zh-TW is a language of Pre-modification), then comes the Verb and the NP as Object (接著根據現代漢語語法，譯文中，由 PP 所呈現的處所論元角色應置於動作單位前方 ─ 因為台灣地區所使用的漢語是一種遵循著前置修飾法的語言 ─ 接著出現動詞，最後是由名詞所呈現的賓語):
1.	[PP 在記憶體內部資料庫中]
2.	[V 儲存]
3.	[NP 代辦事項]
So-called 'ungrammatical' is described below (所謂「文法錯誤」簡述如下):

In the contributor's suggestion, they tried to use the phrase [在使用記憶體做為資料庫] to convey the meaning of [in an in-memory database], which is incorrect. [使用記憶體做為資料庫] is a complete verb phrase by itself, and merely prefixed by a '在' couldn't make it serving as an Adverbial as what the [PP 在記憶體內部資料庫中] do, since [在使用記憶體做為資料庫] is incomplete and too vague. (在 contributor 的建議中，她/他試圖以 [在使用記憶體做為資料庫] 這個片語來含括 [in an in-memory database] 的語意，但這是不正確的。[使用記憶體做為資料庫] 本身已是個完全動詞片語，只透過「在」作為前綴是沒辦法讓它如 [PP 在記憶體內部資料庫中] 一般充任狀語的，這是因為 [在使用記憶體做為資料庫] 是個尚未完全的單位，意思也過於模糊。)

At least there should be [在使用記憶體做為資料庫時], or [在使用記憶體做為資料庫的地方]. Or even delete the [在], and use the Conj. [而] to bring up the second verb phrase. (至少應該是 [在使用記憶體做為資料庫時] 或者 [在使用記憶體做為資料庫的地方]，甚至刪掉 [在]，改用 [而] 來銜接下句。)

That is why we couldn't take this suggestion. (這便是我們無法採納此建議的原因。) "


In case of any question please feel free to contact us

Thank you for your support
Microsoft C&E Localization Team

**Pull request closed without merging**
