### PR TITLE
Update start-mvc.md

### PR DESCRIPTION
**Pull request by chanmmn**
Following the English version https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?tabs=aspnetcore2x.
Regards

### CODE REVIEW

**Comment by v-radelg** [comment]
Hi @chanmmn , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@chanmmn  Thank you for your feedback and suggestion! 
		
Our language moderator said the zh-TW webpage the contribution is based upon is obsolete. The paragraph in question in current zh-TW webpage is similar to the suggestion. We are closing this PR.
		
Microsoft C&E Localization Team

**Comment by Sara-Nicolini** [comment]
@v-radelg, can you please clarify your comment. Is the feedback from @chanmmn related to content that does no longer exist on the page because the original English topic was updated? If so, can you please indicate what the original content with its suggestion and what the new content is. Thanks

**Comment by Sara-Nicolini** [comment]
@chanmmn, please sign the CLA otherwise we cannot include your changes if they are accepted.
https://cla.dotnetfoundation.org/aspnet/Docs.zh-tw?pullRequest=27

**Comment by chanmmn** [comment]
"The URL in the browser shows localhost:5000." Was what originally did not exist. I added and accepted by the English version. Thanks

**Comment by v-radelg** [comment]
Hi @chanmmn 

The page was recently updated and the string in question was fixed. Your feedback is considered for future files.

Please see the comparative below:

old source:
>* Visual Studio starts [IIS Express](https://docs.microsoft.com/iis/extensions/introduction-to-iis-express/iis-express-overview) and runs your app. Notice that the address bar shows `localhost:port#` and not something like `example.com`. That's because `localhost` is the standard hostname for your local computer. When Visual Studio creates a web project, a random port is used for the web server. In the image above, the port number is 5000. When you run the app, you'll see a different port number.

old original translation:
>* Visual Studio 會啟動 [IIS Express](https://docs.microsoft.com/iis/extensions/introduction-to-iis-express/iis-express-overview)，並執行您的應用程式。 請注意，位址列會顯示 `localhost:port#`，而不是類似於 `example.com` 的內容。 這是因為 `localhost` 是本機電腦的標準主機名稱。 當 Visual Studio 建立 Web 專案時，會對網頁伺服器使用隨機連接埠。 在上圖中，連接埠號碼為 5000。 當您執行應用程式時，會看到不同的連接埠編號。

suggestion:
>* Visual Studio 會啟動 [IIS Express](https://docs.microsoft.com/iis/extensions/introduction-to-iis-express/iis-express-overview)，並執行您的應用程式。 請注意，位址列會顯示 `localhost:port#`，而不是類似於 `example.com` 的內容。 這是因為 `localhost` 是本機電腦的標準主機名稱。 當 Visual Studio 建立 Web 專案時，會對網頁伺服器使用隨機連接埠。 在上圖中，連接埠號碼為 5000，瀏覽器中的網址顯示localhost：5000。 當您執行應用程式時，會看到不同的連接埠編號。

New source: 
>* Visual Studio starts [IIS Express](https://docs.microsoft.com/iis/extensions/introduction-to-iis-express/iis-express-overview) and runs your app. Notice that the address bar shows `localhost:port#` and not something like `example.com`. That's because `localhost` is the standard hostname for your local computer. When Visual Studio creates a web project, a random port is used for the web server. In the image above, the port number is 5000. The URL in the browser shows `localhost:5000`. When you run the app, you'll see a different port number.

Current translation:
>* Visual Studio 會啟動 [IIS Express](https://docs.microsoft.com/iis/extensions/introduction-to-iis-express/iis-express-overview)，並執行您的應用程式。 請注意，位址列會顯示 `localhost:port#`，而不是類似於 `example.com` 的內容。 這是因為 `localhost` 是本機電腦的標準主機名稱。 當 Visual Studio 建立 Web 專案時，會對網頁伺服器使用隨機連接埠。 在上圖中，連接埠號碼為 5000。 瀏覽器中的 URL 顯示`localhost:5000`。 當您執行應用程式時，會看到不同的連接埠編號。

Please feel free to review the new content and create new suggestions if needed.

Thank you
Microsoft C&E Localization Team

**Pull request closed without merging**
