### PR TITLE
調整中文敘述

### PR DESCRIPTION
**Pull request by SkyChang**
部分中文敘述語義不順暢，進行調整

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C22%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201710221550443420-10%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hDEntZAWijHZD2SI9uE7FvKPND41NMBOFrUmH38%2BXto%3D&st=2017-10-22T15%3A45%3A47Z&se=2017-11-22T15%3A50%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
@SkyChang ：感謝您的意見反應及建議！   	  	

我們十分重視您的意見反應，同時對您的意見反應進行部分調整，以便符合 Microsoft 樣式指南。我們會在下次當地語系化時發佈此文章。  	  

Microsoft C&E 當地語系化小組敬上

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C27%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201710272007381794-10%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Cxhm45Tyjdryokv%2BsuejIEfHwbjlh27w6%2FHRkgAZvf8%3D&st=2017-10-27T20%3A02%3A41Z&se=2017-11-27T20%3A07%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
@SkyChang , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
