### PR TITLE
修正中文語意

### PR DESCRIPTION
**Pull request by SkyChang**
ASP.NET 核心模組必須安裝在 IIS 伺服器上，或開發電腦上的 IIS Express 。 針對伺服器，ANCM 隨附於[.NET 核心 Windows Server 裝載配套](https://aka.ms/dotnetcore.2.0.0-windowshosting)。 針對開發電腦， Visual Studio 會自動安裝 ANCM 在 IIS Express 中，如果電腦上已經安裝 IIS 也會安裝。
原文為
ASP.NET 核心模組必須安裝在 IIS 伺服器上，並在 IIS Express 開發電腦上。 針對伺服器，ANCM 隨附於.NET 核心 Windows Server 裝載配套。 開發電腦的 Visual Studio 會自動安裝 ANCM 在 IIS Express 中，並在 IIS 中如果已安裝在電腦上。

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C30%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201710301605140642-15%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IpKgKZVvg1XS8xEVlYT7asOjiU7YrShAESLMsLs9agQ%3D&st=2017-10-30T16%3A00%3A16Z&se=2017-11-30T16%3A05%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
@SkyChang  您好，我們仍然在討論您的建議，會儘速於稍後做出結論。  	  	
感謝您的支持，  Microsoft C&E 當地語系化小組敬上

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711061938587881-15%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Xa2HQOVub7%2BK4qWhQUv%2B3ugLL6SmhrDnFrxp6%2BdyiyU%3D&st=2017-11-06T19%3A34%3A42Z&se=2017-12-07T19%3A39%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711061939407359-15%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kmAH2D9tfy4oH8Ux7rqaehXE6tIXUAIEwUzzcChcLZk%3D&st=2017-11-06T19%3A35%3A24Z&se=2017-12-07T19%3A40%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711061940232788-15%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Az%2BFnFKX%2FrWPds6OdDDZPDbJKhV0ynnwsNU1dFGy7ZM%3D&st=2017-11-06T19%3A35%3A55Z&se=2017-12-07T19%3A40%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C6%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711061941019759-15%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HF7ppAqBTMaS4SwMSyAQWsDnxGnoSQn%2FxY7mB1leanY%3D&st=2017-11-06T19%3A36%3A29Z&se=2017-12-07T19%3A41%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
@SkyChang ：感謝您的意見反應及建議！   	  	
我們十分重視您的意見反應，同時對您的意見反應進行部分調整，以便符合 Microsoft 樣式指南。我們會在下次當地語系化時發佈此文章。  	  
Microsoft C&E 當地語系化小組敬上

**Pull request merged**
