### PR TITLE
Update.

### PR DESCRIPTION
**Pull request by yinnping**
Make the sentence more fluent.

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C28%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711280726163969-21%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jfRgI%2F5qINVoLc9Jy%2BL5nIoS44qWhlDZ5urFwLjMfsY%3D&st=2017-11-28T07%3A21%3A19Z&se=2017-12-29T07%3A26%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C28%5Ce23f39d1-5894-af9a-ac11-c18c429b7cae%5CPullRequest%5C201711280736481529-21%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ipVRlK%2BjjbE5yJX2K1%2FOWT90ceFwm2kmX9n7aU9ldDQ%3D&st=2017-11-28T07%3A31%3A50Z&se=2017-12-29T07%3A36%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @yinnping , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@ Thank you for your feedback and suggestion! 
		
Our language moderator disagreed with the change for being preferential and for the omission of the word 'using.' We are closing this PR. 
		
Microsoft C&E Localization Team

**Pull request closed without merging**
